### ISSUE TITLE
We cannot get it running

### ISSUE THREAD

**Issue by jescorotero** [q2g/q2g-con-hypercube-qvx#20]
Hi 
I'm sorry, but after following the instructions we didn't get it work.

1. The .zip downloaded has several folders, not only this connector.  
we stopped the services, we unzip into the server folder  C:\Program Files (x86)\Common Files\Qlik\Custom Data .  we start again the services.  The connector is not shown.

2 . If we move the extracted connector folder q2gConHypercubeQVX into the C:\Program Files (x86)\Common Files\Qlik\Custom folder (C:\Program Files (x86)\Common Files\Qlik\Custom\q2gConHypercubeQVX ), then the connector appears in the "new connection" dialog. but after choose Q2G Sense App connector, nothing happens and dialog closes.

3 . We have tried to move then to the C:\Program Files\Common Files\Qlik\Custom Data folder, when we can see other connectors there. But with the same result, after click on the connector, nothing happens.

We are using QS Enterprise February version 

Any suggestion ?

Thanks

**Comment by konne** [comment]
Hi,

1.  C:\Program Files\Common Files\Qlik should be the right place for Sense Server, I have fixed the Readme
2. please stop step by step all Services including Qlik Repository Service,... wait a little bit, restart this. We have some troubles to get new connector running the first time after install since the Nov2017 Sense release

If you have still trouble contact us again.

**Comment by jescorotero** [comment]
we tried with 1) and after restarting the server, not only the services, the answer is the same, we see the connector, but when click on it for creating a new connection it closes suddenly.

**Comment by konne** [comment]
Hi, I really like to see it in a webex / teamviewer, please write you email, so that we can contact your for a meeting.

bye

**Comment by jescorotero** [comment]
Hi @konne 

No problem, 

We can meet by teamviewer 

My skype is jescorotero

**Comment by konne** [comment]
Hi,
@jescorotero we have found the issue with Qlik Feb 2018 and fixed it.
Please donwload the new extension package version.

**Comment by jescorotero** [comment]
I will.  Have you merged it? I didn't see any change at GH.  Anyway, I will download again and try it.

**Comment by jescorotero** [comment]
@konne Now, we can create the connection and when choosing datasources, we can see the apps, and the tables, and the metadata, but we cannnot see the preview and after save to script and run the suggested sql code, an error stops the load 

The log says

System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en QlikView.Qvx.QvxLibrary.QvxTable.Transmit(Stream stream)
   en QlikView.Qvx.QvxLibrary.QvxConnection.TransmitTableHeader(QvxDataTable data, Stream pipeStream)
   en QlikView.Qvx.QvxLibrary.QvxConnection.Execute(String query, String dataPipeName, String extraParamters, Action`1 onError, Action clearMExecuteError)
   en QlikView.Qvx.QvxLibrary.QvxServer.HandleExecute(QvxRequest request)
   en QlikView.Qvx.QvxLibrary.QvxServer.HandleRequest(QvxRequest request)
   en QlikView.Qvx.QvxLibrary.QvxServer.Run(String parentString, String pipeName)

What are we doing wrong ?

Thanks

**Comment by konne** [comment]
@jescorotero yesterday I didn't uploaded the changes, they are now online.
Your error is strange, I will check it later today

**Comment by konne** [comment]
@jescorotero I didn't had time yesterday, but I will take care today

**Comment by konne** [comment]
@jescorotero  I did't forgort you, I will come back tomorrow on that problems

**Comment by jescorotero** [comment]
Ok, thanks
ᐧ



Jesús Correa
Guía Buscorestaurantes
http://www.buscorestaurantes.com - jesus@buscorestaurantes.com
Tel: 931810266  - Fax: 935504013

<http://twitter.com/#%21/buscorest>
<http://www.facebook.com/pages/Buscorestaurantescom/56620281104>



2018-04-10 17:18 GMT+02:00 Konrad Mattheis <notifications@github.com>:

**Comment by mossbeard** [comment]
@WalterColeman 
Hi,
I suspect that the connector is not in the correct directory. If you are using the desktop version, copy the connector to the directory "C:\Users\<USERNAME>\AppData\Local\Programs\Common Files\Qlik\Custom Data". If you have the server version, copy the connector to the directory "C:\Program Files\Common Files\Qlik\Custom Data".
I hope I could help you.

**Comment by phani221984** [comment]
i dont see this working in Nov 2018 QS server. i dont see in connector in data load editor when i try to create a new connection.

**Comment by mossbeard** [comment]
@phani221984 
Hi, 
copy the connector to the folder C:\Program Files\Common Files\Qlik\Custom Data
![grafik](https://user-images.githubusercontent.com/26477924/52791272-d7658f00-3068-11e9-9bc1-0c21af131e5b.png)
Have you restart the qlik services?
I hope I could help you.

**Comment by phuoctm** [comment]
Hi @konne , this is a great connector but unfortunately I only got it to work on desktop and we desperately need it for server!

On server I couldn't get any success, looks like same error as @jescorotero : I can select database (=app), table (=object), see the metadata and insert script, but cannot see any data preview and when reloading, I get 
"QVX_UNKNOWN_ERROR: Object reference not set":
![image](https://user-images.githubusercontent.com/50193515/57059449-21502f80-6cbe-11e9-9142-42259b1a353b.png)

Has anyone got this working after the above error, how?

Thanks for your help!

**Comment by mossbeard** [comment]
@phuoctm 
Hi,
is this the right app name?
At least one more .qvf would have to be hung on it.
Like this example
SQL SELECT "Product"
    ,"Inventory Turns"
    ,"Inventory Amount"
    ,"Margin %"
FROM [**Executive Dashboard.qvf**].[JZMrdb];

Which Qlik Enterprise version do you have?

Thank you for your interest for our connector

**Comment by phuoctm** [comment]
Thanks for the quick response! I am using Enterprise version Nov 2018 Patch 3 (12.44.5).

My example select statement was created using the connector's "insert script" feature, should it contain the ".qvf" also when connecting to server? I am assuming that my connector configuration is correct because the connector correctly lists all apps and objects from the server, just data preview and actual loading fails.

Unfortunately I do not have Executive Dashboard on server (customer environment managed by 3rd party so I have limited rights). I also tried adding the .qvf ending and even with appid but it produced exactly same error message:
![image](https://user-images.githubusercontent.com/50193515/57122737-74da8000-6d87-11e9-8602-43ed62788d6e.png)

**Comment by mossbeard** [comment]
Hi,
we have fixed 2 bug in the Connector.
Please test the new master Branch version.
Please check your user credentials like this screenshot.

![grafik](https://user-images.githubusercontent.com/26477924/57428740-020b5200-722a-11e9-86ba-780ba630f287.png)

Let me know if it works now.

**Comment by phuoctm** [comment]
Thanks for the quick fix! Did you mean that I should get the latest source code and compile it? Unfortunately I don't have visual studio, so could you please send me a link to the latest install package?

**Comment by mossbeard** [comment]
In **one week** it will also be included in the Extension Bundle.
Under the following link: https://m.sense2go.net/extension-package
If we can do it sooner, I'll will contact you

**Comment by mossbeard** [comment]
@phuoctm
So here is the link to the current version.
https://m.sense2go.net/asset/47:q2g-con-hypercube-qvxzip

**Comment by phuoctm** [comment]
Hi @mossbeard , unfortunately it still isn't working after installing the version above, and actually now the "Select data" wizard stopped working as well ie. I can't select any DB/app like I was able to do before. Both trying old data connection or query or creating new ones doesn't work.

Could you please check if I have the correct version number in my screenshot below?

I don't have access rights to install connectors on server and reboot it, so that is why it took so long to test this new version. We do still have an urgent need to get this working, though, any chance of getting a fix soon?

![image](https://user-images.githubusercontent.com/50193515/58782452-561a1400-85e7-11e9-8810-acf551bed72a.png)

**Comment by phuoctm** [comment]
Hi @mossbeard 

> So here is the link to the current version.
> https://m.sense2go.net/asset/47:q2g-con-hypercube-qvxzip

I tried the above version now also on Desktop (Sense April 2019 version) and it doesn't work there either. In fact, I couldn't open the Sense Desktop at all when I copied this connector version to:
C:\Users\Fuki\AppData\Local\Programs\Common Files\Qlik\Custom Data

This latest version seems unstable? The 1.1 version was working fine on April 2019 desktop, unfortunately it just didn't work on Sense server.

**Comment by phuoctm** [comment]
Hi @mossbeard,

This would be so useful for us, if only it worked on server and not just desktop. Any chance of getting a fix soon?

**Comment by nileshlathiya** [comment]
Hi @mossbeard,
This seems very good connector and thanks for creating this. I really want this for Server version. Any chance for getting this working for Server ?

**Comment by phuoctm** [comment]
Sorry to see this very promising connector abandoned? No working version or responses in months?

**Comment by pablodelcerro** [comment]
I´ve got it to work using on the host address: wss://SERVERNAME:4747/app/

**Comment by jcorrea-tkww** [comment]
@pablodelcerro I have just tried your workaround and it worked for me as well.  I have several projects when this extension could be useful to retrieve and consume data ready to be pulled from other apps and currently we se nprinting to get this working  If this works it saves a lot of time and dependencies.  Thank you so much for sharing the workaround. Hugs.

**Comment by pablodelcerro** [comment]
@jescorotero te respondo en español ya que entiendo sos de españa y yo de argentina... Me alegro te haya funcionado, nosotros también evaluamos NPrinting en caso de que esto no funcione, pero de esta manera nos ahorramos pasos intermedios.
Proximamente pretendo que gente de mi equipo evalue el conector para poder entender mas como funciona en caso de que haya algún problema futuro, y así tratar de continuar con el trabajo de @konne 
Manejo una consultora Qlik en Argentina y España, por lo que si te puedo ayudar en algo no dudes en contactarme.
Slds
Pablo
